begin;

create table if not exists public.field_types (
  id bigint generated by default as identity primary key,
  name character varying
);

create table if not exists public.fish (
  id bigint generated by default as identity primary key,
  name character varying,
  field_type_id bigint,
  constraint fish_field_type_id_fkey
    foreign key (field_type_id)
    references public.field_types(id),
  constraint fish_id_field_type_id_key
    unique (id, field_type_id)
);

create table if not exists public.profiles (
  id uuid primary key,
  nickname text,
  birth_year integer,
  main_genre text,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint profiles_id_fkey
    foreign key (id)
    references auth.users(id)
    on delete cascade
);

insert into public.field_types (id, name)
values
  (1, '바다'),
  (2, '민물')
on conflict (id) do update
set name = excluded.name;

insert into public.fish (id, name, field_type_id)
values
  (1, '우럭', 1),
  (2, '광어', 1),
  (3, '참돔', 1),
  (4, '고등어', 1),
  (5, '갈치', 1),
  (6, '농어', 1),
  (7, '방어', 1),
  (8, '볼락', 1),
  (9, '도다리', 1),
  (10, '삼치', 1),
  (11, '벵에돔', 1),
  (12, '돌돔', 1),
  (13, '전어', 1),
  (14, '전갱이', 1),
  (15, '쥐노래미', 1),
  (16, '노래미', 1),
  (17, '붕장어', 1),
  (18, '부시리', 1),
  (19, '잿방어', 1),
  (20, '점농어', 1),
  (21, '긴꼬리벵에돔', 1),
  (22, '숭어', 1),
  (23, '가숭어', 1),
  (24, '쥐치', 1),
  (25, '말쥐치', 1),
  (26, '임연수어', 1),
  (27, '대구', 1),
  (28, '능성어', 1),
  (29, '붉바리', 1),
  (30, '자바리', 1),
  (31, '강담돔', 1),
  (32, '민어', 1),
  (33, '옥돔', 1),
  (34, '성대', 1),
  (35, '양태', 1),
  (36, '쏨뱅이', 1),
  (37, '쑤기미', 1),
  (38, '보리멸', 1),
  (39, '띠볼락', 1),
  (40, '만새기', 1),
  (41, '달고기', 1),
  (42, '백조기', 1),
  (43, '부세', 1),
  (44, '수조기', 1),
  (45, '참가자미', 1),
  (46, '강도다리', 1),
  (47, '학꽁치', 1),
  (48, '무늬오징어', 1),
  (49, '갑오징어', 1),
  (50, '한치', 1),
  (51, '살오징어', 1),
  (52, '주꾸미', 1),
  (53, '낙지', 1),
  (54, '돌문어', 1),
  (55, '참문어', 1),
  (56, '피문어', 1),
  (57, '배스', 2),
  (58, '토종붕어', 2),
  (59, '쏘가리', 2),
  (60, '잉어', 2),
  (61, '떡붕어', 2),
  (62, '향어', 2),
  (63, '가물치', 2),
  (64, '송어', 2),
  (65, '산천어', 2),
  (66, '꺽지', 2),
  (67, '메기', 2),
  (68, '빙어', 2),
  (69, '강준치', 2),
  (70, '끄리', 2),
  (71, '피라미', 2),
  (72, '갈겨니', 2),
  (73, '블루길', 2)
on conflict (id) do update
set
  field_type_id = excluded.field_type_id,
  name = excluded.name;

select setval(
  pg_get_serial_sequence('public.field_types', 'id'),
  (select max(id) from public.field_types),
  true
);

select setval(
  pg_get_serial_sequence('public.fish', 'id'),
  (select max(id) from public.fish),
  true
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

alter table public.field_types enable row level security;
alter table public.fish enable row level security;
alter table public.profiles enable row level security;

grant all on table public.field_types to anon, authenticated;
grant all on table public.fish to anon, authenticated;
grant all on table public.profiles to anon, authenticated;

drop policy if exists "Enable read access for all users" on public.field_types;
create policy "Enable read access for all users"
on public.field_types
for select
to public
using (true);

drop policy if exists "Enable read access for all users" on public.fish;
create policy "Enable read access for all users"
on public.fish
for select
to public
using (true);

drop policy if exists "누구나 프로필 조회 가능" on public.profiles;
create policy "누구나 프로필 조회 가능"
on public.profiles
for select
to public
using (true);

drop policy if exists "본인 프로필만 생성 가능" on public.profiles;
create policy "본인 프로필만 생성 가능"
on public.profiles
for insert
to public
with check (auth.uid() = id);

drop policy if exists "본인만 프로필 수정 가능" on public.profiles;
create policy "본인만 프로필 수정 가능"
on public.profiles
for update
to public
using (auth.uid() = id);

commit;
