begin;

drop function if exists public.create_fishing_log_from_form(
  bigint,
  text,
  date,
  time without time zone,
  text,
  text,
  integer,
  numeric,
  text,
  numeric,
  double precision,
  double precision,
  text
);

drop function if exists public.create_fishing_log(
  bigint,
  timestamp with time zone,
  bigint,
  text,
  integer,
  numeric,
  text,
  text,
  numeric,
  text,
  double precision,
  double precision,
  text,
  text
);

drop table if exists public.fishing_log_catches cascade;
drop table if exists public.fishing_logs cascade;
drop function if exists public.set_fishing_logs_updated_at();

create table public.fishing_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  field_type_id bigint not null references public.field_types(id),
  occurred_at timestamp with time zone not null,
  target_fish_id bigint,
  custom_target_fish_name text,
  method text,
  weather text not null,
  tide text,
  water_temperature_c numeric,
  location_name text not null,
  latitude double precision,
  longitude double precision,
  memo text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint fishing_logs_target_fish_field_type_fkey
    foreign key (target_fish_id, field_type_id)
    references public.fish(id, field_type_id),
  constraint fishing_logs_target_fish_or_custom_check
    check (
      target_fish_id is not null
      or nullif(btrim(custom_target_fish_name), '') is not null
    ),
  constraint fishing_logs_weather_required_check
    check (nullif(btrim(weather), '') is not null),
  constraint fishing_logs_location_name_required_check
    check (nullif(btrim(location_name), '') is not null),
  constraint fishing_logs_coordinates_pair_check
    check (
      (latitude is null and longitude is null)
      or (latitude is not null and longitude is not null)
    ),
  constraint fishing_logs_latitude_range_check
    check (latitude is null or (latitude >= -90 and latitude <= 90)),
  constraint fishing_logs_longitude_range_check
    check (longitude is null or (longitude >= -180 and longitude <= 180))
);

create table public.fishing_log_catches (
  id bigint generated by default as identity primary key,
  log_id bigint not null references public.fishing_logs(id) on delete cascade,
  fish_id bigint references public.fish(id),
  custom_fish_name text,
  catch_count integer not null,
  max_size_cm numeric,
  created_at timestamp with time zone not null default now(),
  constraint fishing_log_catches_fish_or_custom_check
    check (
      fish_id is not null
      or nullif(btrim(custom_fish_name), '') is not null
    ),
  constraint fishing_log_catches_count_positive_check
    check (catch_count > 0),
  constraint fishing_log_catches_max_size_check
    check (max_size_cm is null or max_size_cm >= 0)
);

create index fishing_logs_user_id_occurred_at_idx
  on public.fishing_logs (user_id, occurred_at desc);

create index fishing_logs_field_type_id_idx
  on public.fishing_logs (field_type_id);

create index fishing_log_catches_log_id_idx
  on public.fishing_log_catches (log_id);

create index fishing_log_catches_fish_id_idx
  on public.fishing_log_catches (fish_id);

create or replace function public.set_fishing_logs_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_fishing_logs_updated_at
before update on public.fishing_logs
for each row
execute function public.set_fishing_logs_updated_at();

alter table public.fishing_logs enable row level security;
alter table public.fishing_log_catches enable row level security;

revoke all on table public.fishing_logs from public;
revoke all on table public.fishing_log_catches from public;

grant select, insert, update, delete on table public.fishing_logs to authenticated;
grant select, insert, update, delete on table public.fishing_log_catches to authenticated;
grant usage, select on sequence public.fishing_logs_id_seq to authenticated;
grant usage, select on sequence public.fishing_log_catches_id_seq to authenticated;

create policy "Users can view own fishing logs"
on public.fishing_logs
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert own fishing logs"
on public.fishing_logs
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update own fishing logs"
on public.fishing_logs
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own fishing logs"
on public.fishing_logs
for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can view own fishing log catches"
on public.fishing_log_catches
for select
to authenticated
using (
  exists (
    select 1
    from public.fishing_logs
    where fishing_logs.id = fishing_log_catches.log_id
      and fishing_logs.user_id = (select auth.uid())
  )
);

create policy "Users can insert own fishing log catches"
on public.fishing_log_catches
for insert
to authenticated
with check (
  exists (
    select 1
    from public.fishing_logs
    where fishing_logs.id = fishing_log_catches.log_id
      and fishing_logs.user_id = (select auth.uid())
  )
);

create policy "Users can update own fishing log catches"
on public.fishing_log_catches
for update
to authenticated
using (
  exists (
    select 1
    from public.fishing_logs
    where fishing_logs.id = fishing_log_catches.log_id
      and fishing_logs.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.fishing_logs
    where fishing_logs.id = fishing_log_catches.log_id
      and fishing_logs.user_id = (select auth.uid())
  )
);

create policy "Users can delete own fishing log catches"
on public.fishing_log_catches
for delete
to authenticated
using (
  exists (
    select 1
    from public.fishing_logs
    where fishing_logs.id = fishing_log_catches.log_id
      and fishing_logs.user_id = (select auth.uid())
  )
);

commit;
