begin;

insert into storage.buckets (
  id,
  name,
  "public",
  file_size_limit,
  allowed_mime_types
)
values (
  'fishing-log-images',
  'fishing-log-images',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  name = excluded.name,
  "public" = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types,
  updated_at = now();

create table if not exists public.fishing_log_images (
  id bigint generated by default as identity primary key,
  log_id bigint not null references public.fishing_logs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_bucket text not null default 'fishing-log-images',
  storage_path text not null,
  original_file_name text,
  content_type text not null,
  size_bytes bigint not null,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  constraint fishing_log_images_bucket_check
    check (storage_bucket = 'fishing-log-images'),
  constraint fishing_log_images_storage_path_required_check
    check (nullif(btrim(storage_path), '') is not null),
  constraint fishing_log_images_storage_path_owner_check
    check (storage_path like user_id::text || '/%'),
  constraint fishing_log_images_original_file_name_check
    check (
      original_file_name is null
      or nullif(btrim(original_file_name), '') is not null
    ),
  constraint fishing_log_images_content_type_check
    check (content_type in ('image/jpeg', 'image/png', 'image/webp')),
  constraint fishing_log_images_size_bytes_check
    check (size_bytes > 0 and size_bytes <= 5242880),
  constraint fishing_log_images_sort_order_check
    check (sort_order >= 0),
  constraint fishing_log_images_storage_object_unique
    unique (storage_bucket, storage_path)
);

create index if not exists fishing_log_images_log_id_sort_order_idx
  on public.fishing_log_images (log_id, sort_order, id);

create index if not exists fishing_log_images_user_id_created_at_idx
  on public.fishing_log_images (user_id, created_at desc);

alter table public.fishing_log_images enable row level security;

revoke all on table public.fishing_log_images from public;
grant select, insert, update, delete on table public.fishing_log_images to authenticated;
grant usage, select on sequence public.fishing_log_images_id_seq to authenticated;

drop policy if exists "Users can view own fishing log images"
on public.fishing_log_images;

create policy "Users can view own fishing log images"
on public.fishing_log_images
for select
to authenticated
using (
  exists (
    select 1
    from public.fishing_logs
    where fishing_logs.id = fishing_log_images.log_id
      and fishing_logs.user_id = (select auth.uid())
  )
);

drop policy if exists "Users can insert own fishing log images"
on public.fishing_log_images;

create policy "Users can insert own fishing log images"
on public.fishing_log_images
for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.fishing_logs
    where fishing_logs.id = fishing_log_images.log_id
      and fishing_logs.user_id = (select auth.uid())
  )
);

drop policy if exists "Users can update own fishing log images"
on public.fishing_log_images;

create policy "Users can update own fishing log images"
on public.fishing_log_images
for update
to authenticated
using (
  exists (
    select 1
    from public.fishing_logs
    where fishing_logs.id = fishing_log_images.log_id
      and fishing_logs.user_id = (select auth.uid())
  )
)
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.fishing_logs
    where fishing_logs.id = fishing_log_images.log_id
      and fishing_logs.user_id = (select auth.uid())
  )
);

drop policy if exists "Users can delete own fishing log images"
on public.fishing_log_images;

create policy "Users can delete own fishing log images"
on public.fishing_log_images
for delete
to authenticated
using (
  exists (
    select 1
    from public.fishing_logs
    where fishing_logs.id = fishing_log_images.log_id
      and fishing_logs.user_id = (select auth.uid())
  )
);

drop policy if exists "Users can view own fishing log storage objects"
on storage.objects;

create policy "Users can view own fishing log storage objects"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'fishing-log-images'
  and (storage.foldername(name))[1] = (select auth.jwt() ->> 'sub')
);

drop policy if exists "Users can upload own fishing log storage objects"
on storage.objects;

create policy "Users can upload own fishing log storage objects"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'fishing-log-images'
  and (storage.foldername(name))[1] = (select auth.jwt() ->> 'sub')
  and (storage.foldername(name))[2] is not null
  and lower(storage.extension(name)) in ('jpg', 'jpeg', 'png', 'webp')
);

drop policy if exists "Users can delete own fishing log storage objects"
on storage.objects;

create policy "Users can delete own fishing log storage objects"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'fishing-log-images'
  and (storage.foldername(name))[1] = (select auth.jwt() ->> 'sub')
);

commit;
